// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Registro_Fecha_Vigencia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Registro_Fecha_Vigencia));
        
        string IMigrationMetadata.Id
        {
            get { return "201604071943321_Registro_Fecha_Vigencia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
