// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Elementos_Aceso_Controlado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Elementos_Aceso_Controlado));
        
        string IMigrationMetadata.Id
        {
            get { return "201606111845452_Elementos_Aceso_Controlado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
