// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Elementos_Acceso_Controlado_Todos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Elementos_Acceso_Controlado_Todos));
        
        string IMigrationMetadata.Id
        {
            get { return "201606122032482_Elementos_Acceso_Controlado_Todos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
