// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cambio_Empresa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cambio_Empresa));
        
        string IMigrationMetadata.Id
        {
            get { return "201603170147350_Cambio_Empresa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
