// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NotaPrevia_Opcional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NotaPrevia_Opcional));
        
        string IMigrationMetadata.Id
        {
            get { return "201603062009556_NotaPrevia_Opcional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
