// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Quitar_CascadeDelete_TiposDocumento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Quitar_CascadeDelete_TiposDocumento));
        
        string IMigrationMetadata.Id
        {
            get { return "201603062148210_Quitar_CascadeDelete_TiposDocumento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
