// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Jornada_Caracteristicas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jornada_Caracteristicas));
        
        string IMigrationMetadata.Id
        {
            get { return "201803122029074_Jornada_Caracteristicas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
