// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nueva_Propiedad_Jornada_Envio_OVAL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nueva_Propiedad_Jornada_Envio_OVAL));
        
        string IMigrationMetadata.Id
        {
            get { return "201907181651362_Nueva_Propiedad_Jornada_Envio_OVAL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
