// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Jornadas_Autorizables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jornadas_Autorizables));
        
        string IMigrationMetadata.Id
        {
            get { return "201905122035145_Jornadas_Autorizables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
