// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nuevas_Propiedades_EnvioOVAL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nuevas_Propiedades_EnvioOVAL));
        
        string IMigrationMetadata.Id
        {
            get { return "201907060004533_Nuevas_Propiedades_EnvioOVAL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
