// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Propiedad_JornadaAutorizada_Mapeada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Propiedad_JornadaAutorizada_Mapeada));
        
        string IMigrationMetadata.Id
        {
            get { return "201905191431527_Propiedad_JornadaAutorizada_Mapeada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
