// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Jornada_CaracteristicasEnIngles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jornada_CaracteristicasEnIngles));
        
        string IMigrationMetadata.Id
        {
            get { return "202007141338081_Jornada_CaracteristicasEnIngles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
