// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Capacitado_Telefono : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Capacitado_Telefono));
        
        string IMigrationMetadata.Id
        {
            get { return "202010121853184_Capacitado_Telefono"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
