// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class PuntoServicio_Rest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PuntoServicio_Rest));
        
        string IMigrationMetadata.Id
        {
            get { return "202112181345450_PuntoServicio_Rest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
