// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Tipo_Punto_Servicio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tipo_Punto_Servicio));
        
        string IMigrationMetadata.Id
        {
            get { return "202111091454580_Tipo_Punto_Servicio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
