// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Curso_EnviarActaEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Curso_EnviarActaEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "202411032137005_Curso_EnviarActaEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
