// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Capacitado_TipoAlmacenamientoFoto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Capacitado_TipoAlmacenamientoFoto));
        
        string IMigrationMetadata.Id
        {
            get { return "202403281900482_Capacitado_TipoAlmacenamientoFoto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
