// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Curso_SinVigencia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Curso_SinVigencia));
        
        string IMigrationMetadata.Id
        {
            get { return "202510030311425_Curso_SinVigencia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
