// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Curso_NotificarVencimiento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Curso_NotificarVencimiento));
        
        string IMigrationMetadata.Id
        {
            get { return "202510170342127_Curso_NotificarVencimiento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
