// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class RegistroCapacitacion_EliminarAprobado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegistroCapacitacion_EliminarAprobado));
        
        string IMigrationMetadata.Id
        {
            get { return "202601201708142_RegistroCapacitacion_EliminarAprobado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
