// <auto-generated />
namespace Cursos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class IntegracionAlutelInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntegracionAlutelInicial));

        string IMigrationMetadata.Id
        {
            get { return "202607171115000_IntegracionAlutelInicial"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
